### ISSUE TITLE
curb installation mac osx-lion

### ISSUE THREAD

**Issue by vpereira** [taf2/curb#104]
I'm trying to install the curb gem in my Mac OSX Lion. I tried all solutions cited here already, like http://stackoverflow.com/questions/2350141/having-issues-with-curb-gem-on-mac-snow-leopard 

my environment ruby 1.9.2 (rvm), mac OSX Lion, Xcode installed, lib curl (through  sudo port install curl +universal command) installed. 

the results from bundle install and my lib curl path is in this gist:

https://gist.github.com/1652989

based on my lib curl installation (as well on gist) I did try as well this compile command:

```
rake install EXTCONF_OPTS='--with-curl-dir=/opt/local/include/curl --prefix=/opt/local'
```

which failed. any idea? why it is so difficult to install it in mac osx? with linux it works like a charm... is the mac osx development environment?

**Comment by dhulihan** [comment]
Not sure if this is helpful, but I was able to successful build curb with brew curl in OSX 10.11.2 (El Capitan)

```sh
brew install curl --with-openssl
brew link curl --force
export PATH=$PATH:/usr/local/bin
gem install curb
```

**Comment by hiroshi** [comment]
In my case,  `~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/curb-0.9.1/mkmf.log` show me `ld: library not found for -lnghttp2`

So I tried `brew install curl --with-openssl --with-nghttp2` and it works!

OS X: El Capitan 10.11.4
homebrew curl 7.48.0

**Comment by pololee** [comment]
I followed this comment https://github.com/taf2/curb/issues/104#issuecomment-204483932
but got the error `make: /usr/local/opt/coreutils/bin/gmkdir: No such file or directory`
After `brew install coreutils`, it works.
