### ISSUE TITLE
set timeout in milliseconds

### ISSUE THREAD

**Issue by armanto** [taf2/curb#162]
Hi,

Is there anyway to set the timeout in milliseconds? If so could telll me how to do it?

I'm using the Curl::Easy

thanks

**Comment by TalLevAmi** [comment]
libcurl has [CURLOPT_TIMEOUT_MS] (http://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT_MS.html) which support receiving the timeout in milliseconds.

**Comment by taf2** [comment]
cool -i'll accept pull requests for that.

**Comment by Kondratenko-Valeriy** [comment]
Hi Todd! Any news about this issue? Cannot find timeout in milliseconds.
