### ISSUE TITLE
Does not work with ruby 2.0

### ISSUE THREAD

**Issue by rumpelsepp** [taf2/curb#165]
With ruby 2.0 I get this

```
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- curb_core (LoadError)
```

**Comment by dhara-thacker** [comment]
I'm having the same issue. Gem installation succeeds, but when I write: 
 require 'curb'
It gives error:

> LoadError: cannot load such file -- curb

Any luck with this?
