### ISSUE TITLE
Installing curb on Windows 7

### ISSUE THREAD

**Issue by roobeedeedada** [taf2/curb#183]
I've not been able to install curb after several attempts, with various (lib)curl libraries, on my Windows system. The last thing I tried:

```
C:>gem install curb --version 0.7.18 --platform=ruby -- -- --with-curl-lib=C:/curl-7.34.0-devel-mingw64/bin --with-curl-include=C:/curl-7.34.0-devel-mingw64/include
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '-- --with-curl-lib=C:/curl-7.34.0-devel-mingw64/bin --with-curl-include=C:/curl-7.34.0-devel-mingw64/include'
This could take a while...
ERROR:  Error installing curb:
    ERROR: Failed to build gem native extension.

C:/Ruby193/bin/ruby.exe extconf.rb -- --with-curl-lib=C:/curl-7.34.0-devel-mingw64/bin --with-curl-include=C:/curl-7.34.0-devel-mingw64/include
checking for curl-config... no
checking for main() in -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.
```

This was after following advice given [here](http://beginrescue.blogspot.co.uk/2010/07/installing-curb-with-ruby-191-in.html) as referenced in [issue 37](https://github.com/taf2/curb/issues/37).

I've also tried cloning the git repository and doing a rake install and then a rake install specifying the location of the curl library:

```
rake install EXTCONF_OPTS='--with-curl-dir=C:/curl-7.34.0-devel-mingw64'
```

which gives me:

```
c:/Ruby193/bin/ruby.exe extconf.rb --with-curl-dir=C:/curl-7.34.0-devel-mingw64
checking for curl-config... no
checking for main() in -lcurl... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=c:/Ruby193/bin/ruby
    --with-curl-dir
    --with-curl-include
    --without-curl-include=${curl-dir}/include
    --with-curl-lib
    --without-curl-lib=${curl-dir}/lib
    --with-curllib
    --without-curllib
c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:619:in `try_func'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:845:in `block in have_library'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
    from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:840:in `have_library'
    from extconf.rb:17:in `<main>'
rake aborted!
Command failed with status (1): [c:/Ruby193/bin/ruby.exe extconf.rb --with-...]
c:/Users/Alina/Documents/Dev/Repos/curb/Rakefile:51:in `block (2 levels) in <top (required)>'
c:/Users/Alina/Documents/Dev/Repos/curb/Rakefile:50:in `chdir'
c:/Users/Alina/Documents/Dev/Repos/curb/Rakefile:50:in `block in <top (required)>'
Tasks: TOP => install => alltests => unittests => compile => ext/curb_core.so => ext/Makefile
(See full trace by running task with --trace)
```

I've got DevKit working with Ruby 1.9.3 and have successfully installed gems with it as a smoke test (rdiscount and bson_ext), unless it's talking about a different set of development tools. Not sure if worth mentioning that curl seems to work as expected and I get the full source back when performing:

```
curl -L www.google.com
```

Any ideas?

**Comment by ccoenen** [comment]
@Eric-Guo the command line worked for me, thanks!
(ruby 2.1.4 32bit + devkit + windows 8.1 64bit + curl 7.39.0-devel-mingw32)

**Comment by ccoenen** [comment]
@roobeedeedada could you give the instructions in my pull request a try? I know it's been a long time since you opened this ticket, but maybe it will help someone else down the road.

**Comment by i2000s** [comment]
I have tried all those instructions on Windows 10, none worked so far! I had the curb and curl working before, and the Windows 10 upgrade ruined everything. Any updates?

**Comment by Eric-Guo** [comment]
@i2000s I didn't have a change to try Windows 10 yet. (also no plan, unless company policy push me to do that), maybe you can try [vagrent](https://www.vagrantup.com/) as alternative?

**Comment by i2000s** [comment]
@Eric-Guo Thank you. I am doing similar thing to avoid interacting with the Windows 10 environment.

**Comment by loqman** [comment]
This worked for me on windows 10 with ruby 2.4.3 i386-mingw32:
[https://github.com/taf2/curb/issues/164#issuecomment-24510938](https://github.com/taf2/curb/issues/164)

**Comment by luke-hill** [comment]
A few tweaks have been added by myself to the README recently to get windows users building easier.

Key takeaways
- Ruby 2.3.3 is the last version which works "nicely", any 2.4 version is likely to struggle.
- Make sure to have forward slashes and run everything from `C:` directory install.
- Check your PATH variables.

If anyone reading has got this gem working on a Ruby 2.4 on Windows please share what you did so we can get it in the README.
