### ISSUE TITLE
Tags for releases

### ISSUE THREAD

**Issue by gingermusketeer** [taf2/curb#216]
Any chance of getting tags for all the releases up on github? Makes working out which version bugs were fixed in a lot easier.

**Comment by agis** [comment]
This is an issue for us too. Please, can you tag releases?

**Comment by olleolleolle** [comment]
We can make a table of the knowledge we can guess from the repository, to make it easy to do:

| Tag | Commit |
| --- | --- |
| 0.9.10 | e4ae981cd26d17c961e2e50e21ff5be49afa484e |
