### ISSUE TITLE
Curl::Err::SSLConnectError: SSL connect error

### ISSUE THREAD

**Issue by epinault** [taf2/curb#217]
So I am using 0.8.6 gem , ruby 2.1.1 and 2.1.3 on ubuntu 12.04 with everything up to date (openssl shows 1.01

But normal http works fine.. https totally fails with error Curl::Err::SSLConnectError: SSL connect error

any idea what that error is?

**Comment by bootstraponline** [comment]
I'm seeing the same issue on OS X.

> /.rvm/gems/ruby-2.2.2/gems/curb-0.8.8/lib/curl/easy.rb:72:in `perform': SSL connect error (Curl::Err::SSLConnectError)

**Comment by taf2** [comment]
@bootstraponline this is usually a system issue or the domain you're requesting has an invalid certificate...

**Comment by bootstraponline** [comment]
It works if I run the same command again. I'm enabling verbose mode so I can see the exact message.
