### ISSUE TITLE
Curb learning to use basic auth when it has not been set

### ISSUE THREAD

**Issue by chrisgame** [taf2/curb#221]
When making a request with username and password without specifying an auth type curb appears to make one request with no auth and then upon receiving a 401 a second request is made using basic auth.

I think the feedback would be better if when a username and password were specified basic auth was the default auth type or if an auth type is not specified no auth type is set. Curb attempting to find the correct auth type automagically will result in a lot of 401's on the target server.

**Comment by taf2** [comment]
not sure I understand the issue/question but to make a request with basic auth is easy with:

```

Curl.get("https://anyurl/....") {|http|
    http.userpwd="#{user}:#{pass}"
}

```
