### ISSUE TITLE
Curb doing GET requests instead of POST after redirection

### ISSUE THREAD

**Issue by javiercr** [taf2/curb#224]
When doing a POST requests to an URL that returns a redirect, all the subsequent POST requests are performed as GET instead of POST.

Example:

```ruby
require 'curb'

@curl = Curl::Easy.new
@curl.verbose = true
@curl.follow_location = true

@curl.url = 'https://www.gudog.com' # Returns a 301 redirect to https://gudog.com
@curl.post

puts "\n\n------- Request 2 -----------\n\n"
@curl.url = 'https://gudog.com'
@curl.post
```

The first URL returns a 301 redirection.

Here is the output:

    * Adding handle: conn: 0x1022a1c00
    * Adding handle: send: 0
    * Adding handle: recv: 0
    * Curl_addHandleToPipeline: length: 1
    * - Conn 0 (0x1022a1c00) send_pipe: 1, recv_pipe: 0
    * About to connect() to www.gudog.com port 443 (#0)
    *   Trying 54.229.184.122...
    * Connected to www.gudog.com (54.229.184.122) port 443 (#0)
    * TLS 1.0 connection using TLS_RSA_WITH_AES_128_CBC_SHA
    * Server certificate: gudog.com
    * Server certificate: COMODO RSA Domain Validation Secure Server CA
    * Server certificate: COMODO RSA Certification Authority
    * Server certificate: AddTrust External CA Root
    > POST / HTTP/1.1
    Host: www.gudog.com
    Accept: */*
    Content-Length: 0
    Content-Type: application/x-www-form-urlencoded

    < HTTP/1.1 301 Moved Permanently
    * Server nginx/1.4.7 is not blacklisted
    < Server: nginx/1.4.7
    < Date: Sun, 02 Nov 2014 19:15:13 GMT
    < Content-Type: text/html
    < Content-Length: 184
    < Connection: keep-alive
    < Location: https://gudog.com/
    * HTTP error before end of send, stop sending
    <
    * Closing connection 0
    * Issue another request to this URL: 'https://gudog.com/'
    * Violate RFC 2616/10.3.2 and switch from POST to GET
    * Adding handle: conn: 0x1022a1c00
    * Adding handle: send: 0
    * Adding handle: recv: 0
    * Curl_addHandleToPipeline: length: 1
    * - Conn 1 (0x1022a1c00) send_pipe: 1, recv_pipe: 0
    * About to connect() to gudog.com port 443 (#1)
    *   Trying 54.229.184.122...
    * Connected to gudog.com (54.229.184.122) port 443 (#1)
    * TLS 1.0 connection using TLS_RSA_WITH_AES_128_CBC_SHA
    * Server certificate: gudog.com
    * Server certificate: COMODO RSA Domain Validation Secure Server CA
    * Server certificate: COMODO RSA Certification Authority
    * Server certificate: AddTrust External CA Root
    > GET / HTTP/1.1
    Host: gudog.com
    Accept: */*

    < HTTP/1.1 200 OK
    * Server nginx/1.4.7 is not blacklisted
    < Server: nginx/1.4.7
    < Date: Sun, 02 Nov 2014 19:15:14 GMT
    < Content-Type: text/html; charset=utf-8
    < Transfer-Encoding: chunked
    < Connection: keep-alive
    < Status: 200 OK
    < X-UA-Compatible: IE=Edge,chrome=1
    < ETag: "0a74950bccf1c18420dcd7ddfd04e710"
    < Cache-Control: max-age=0, private, must-revalidate
    < Set-Cookie: _session_id=b46c10c2becac251bde9912f5a94633d; path=/; HttpOnly
    < X-Request-Id: 37e0541a66cacc1ede72e4a91adc70bb
    < X-Runtime: 0.616349
    < X-Rack-Cache: miss
    <
    * Connection #1 to host gudog.com left intact

    ------- Request 2 -----------

    * Found bundle for host gudog.com: 0x102a53e80
    * Re-using existing connection! (#1) with host gudog.com
    * Connected to gudog.com (54.229.184.122) port 443 (#1)
    * Adding handle: conn: 0x1022a1c00
    * Adding handle: send: 0
    * Adding handle: recv: 0
    * Curl_addHandleToPipeline: length: 1
    * - Conn 1 (0x1022a1c00) send_pipe: 1, recv_pipe: 0
    > GET / HTTP/1.1
    Host: gudog.com
    Accept: */*

    < HTTP/1.1 200 OK
    * Server nginx/1.4.7 is not blacklisted
    < Server: nginx/1.4.7
    < Date: Sun, 02 Nov 2014 19:15:15 GMT
    < Content-Type: text/html; charset=utf-8
    < Transfer-Encoding: chunked
    < Connection: keep-alive
    < Status: 200 OK
    < X-UA-Compatible: IE=Edge,chrome=1
    < ETag: "2873d60118356367c57c156f355211d5"
    < Cache-Control: max-age=0, private, must-revalidate
    < Set-Cookie: _session_id=b2416089cb8162a6d9faf08408732329; path=/; HttpOnly
    < X-Request-Id: dac7a78ad8638ca5e7ee4d714b76f8c0
    < X-Runtime: 0.702233
    < X-Rack-Cache: miss
    <
    * Connection #1 to host gudog.com left intact

Note how *after Request 2* you can see:

    > GET / HTTP/1.1

Why is it doing a GET request if I'm performing a POST one?

**Comment by sriedel** [comment]
What you're describing is correct HTTP behaviour. The server should return a 307 or 308 if the http method should not change after the redirect.
