### ISSUE TITLE
Headers Change after signing request

### ISSUE THREAD

**Issue by JWesorick** [taf2/curb#231]
I need to sign requests to my api using [HAMC](http://en.wikipedia.org/wiki/Hash-based_message_authentication_code) but the Content-Type header changes inside of the http_post causing my authentication to fail because the headers I'm using to sign the request don't match the ones getting sent to the server. How can I set the Content-Type and boundary myself, or sign the request after all headers are filled in?

``` ruby
c = Curl::Easy.new("http://api.example.com/stuff")
c.multipart_form_post = true
c.headers["Content-Type"] = "multipart/form-data" # signing headers with this
signed_request = ApiAuth.sign!(c, "pk_XXXX", "sk_XXXX")
c.http_post(Curl::PostField.file('photo[image]', 'lib/test.jpg'))
```

``` ruby
# server gets this
Content-Type: multipart/form-data; boundary=------------------------9164ab6576744d11
```

**Comment by taf2** [comment]
Hi Jake,

  You can probably do something like: 

```
      http = Curl::Easy.new(self.value)
      http.connect_timeout = 8 # 8 second connection timeout
      http.timeout = 18 # 18 second timeout
      digest = OpenSSL::Digest.new('sha1')
      post_body = "multi-part form post data"
      http.headers['Content-Signature'] = Base64.encode64(OpenSSL::HMAC.digest(digest, account.auth_token, post_body)).strip
      http.on_header {|d| d.size }
      http.on_body {|d| d.size }
      http.post_body = post_body
```

I'm not sure though which headers are we manipulating.  If you run the above in c.verbose=true and then maybe can see which header is different from what you're sending.

**Comment by JWesorick** [comment]
Sorry for the huge gap in time. Just getting back to this. The header that is different is the content type. I'm setting it with `c.headers["Content-Type"] = "multipart/form-data"` but the boundary is being added right when it is posted, `Content-Type: multipart/form-data; boundary=------------------------9164ab6576744d11`. Is there a way to know what the boundary will be before posting?

**Comment by taf2** [comment]
I have to try but yes can you try:

```
c.headers["Content-Type"] = multipart/form-data; boundary=----------------------------4ebf00fbcf09" 
```
that at least is how it' done with command line... maybe via libcurl same?
