### ISSUE TITLE
Enable URI parsing

### ISSUE THREAD

**Issue by tmaier** [taf2/curb#246]
Curb should support parsing of `URI`

```ruby
c = Curl::Easy.new(URI('http://github.com/'))
d = Curl::Easy.new(URI('http://user:pw@github.com/'))
```

**Comment by taf2** [comment]
is this already part of ruby?  http://ruby-doc.org/stdlib-1.9.3/libdoc/uri/rdoc/URI.html#method-c-parse

**Comment by tmaier** [comment]
sure!

But Curl must be able to parse it. It should also digest the username and password provided.

Btw. `URL('http://www.example.com')` is a shorthand for `URL::parse('http://www.example.com')`

**Comment by lukeasrodgers** [comment]
This seems out of scope for Curb.

**Comment by taf2** [comment]
see: http://curl.haxx.se/mail/lib-2004-01/0205.html
