### ISSUE TITLE
how do i do bearer token authentication

### ISSUE THREAD

**Issue by angelacode** [taf2/curb#254]
how do i do bearer token authentication?

**Comment by taf2** [comment]
You would want to set the Authentication header e.g.
http.headers["Authentication"]="Bearer
your token here"

On Friday, August 14, 2015, angelacode <notifications@github.com> wrote:

> how do i do bearer token authentication?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taf2/curb/issues/254>.
>


-- 
*Todd Fisher*
Tel: +1 (410) 394-9424 | Toll Free: +1 (800) 577-1872
todd@calltrackingmetrics.com | calltrackingmetrics.com

**Comment by angelacode** [comment]
ah, cool, thanks!
