### ISSUE TITLE
Cookies not working correctly?

### ISSUE THREAD

**Issue by dallasrpi** [taf2/curb#257]
c = Curl::Easy.new
c.url = "http://somesite.com"
c.cookiefile = "cookies.txt"
c.cookiejar  = "cookies.txt"
c.enable_cookies = true
c.perform
c.body_str

File.exists?("cookies.txt")   ---> returns false

It does create the cookie file but not until the script exits.  If I want to make another request in the same script using the cookie I'm out of luck.

**Comment by taf2** [comment]
```
res = Curl.get("http://example.com/")
cookies = {}
res.header_str.split("\r\n").select {|line| line.match(/Set-Cookie:/) }.each {|line| 
  parts = line.sub(/Set-Cookie:\s*/,'').split(';').first.split("=")
  cookies[parts.shift] = parts.join("=")
}
```
