### ISSUE TITLE
POST data using TLS1.2

### ISSUE THREAD

**Issue by thuringian** [taf2/curb#258]
Is it possible to specify TLS 1.2 when using curb? I'm calling an API that requires I use TLS 1.2. I've tried setting curl.ssl_version like the code below but this doesn't seem to work. I keep getting an SSL connection error.

c = Curl::Easy.http_post(ENV['URL'], requestxml) do |curl|
	curl.timeout = 30
	curl.ssl_verify_peer = true
	curl.ssl_version = 3.3
	curl.verbose = true
	curl.headers["Content-Type"] = 'text/xml'
	curl.on_complete {
		response = Nokogiri::XML.parse(curl.body_str.to_s)
	}
end

**Comment by justincase** [comment]
Try `curl.ssl_version = 6` which refers to `CURL_SSLVERSION_TLSv1_2`[[source](https://github.com/bagder/curl/blob/d31ed6ac719cd3c7c1dcac5f9000b19536087b7e/include/curl/curl.h#L1757)]. This libcurl constant doesn't appear to be supported by Curb at this time.

Nevertheless, `Curl::CURL_SSLVERSION_TLSv1 # => 1` should work as it refers to `TLS 1.x` and "means [...] as high as possible but no less than 1.0". See https://github.com/bagder/curl/pull/79#issuecomment-24868931.
