### ISSUE TITLE
how Curb post nested JSON?

### ISSUE THREAD

**Issue by edyywang** [taf2/curb#275]
using Curb to do http_post
````
curl = Curl::Easy.new(url)
curl.headers["Content-Type"] = "application/json"
curl.http_post(params.to_json)
````

The params is a Hash like this
````
{
  system:"some_system",
  details:{
     some_detail:"yes123"
  }
}
````
The http_post request body params.to_json prints out like this
````
{"system":"some_system","details":{"some_detail":"yes123"}}
````
The exact same JSON data works for curl command and postman, but in the Curb's curl.http_post method, I got the error TypeError: no implicit conversion of String into Integer

So I guess sending Nested JSON in Curb caused this, but I have no idea how to send a nested JSON in Curb http_post.

Please help. Thanks

**Comment by taf2** [comment]
```
Curl.post(url, {obj:"value"})
```
