### ISSUE TITLE
Cannot compile curb-0.9.1 on CentOS 5

### ISSUE THREAD

**Issue by awaltman** [taf2/curb#287]
There are two definitions that are used in curb_easy.c that are not available in the version of curl/curl.h available on CentOS 5, CURLOPT_TIMEOUT_MS and CURLOPT_CONNECTTIMEOUT_MS. It looks like the check in extconf.rb is working correctly:

checking for curlopt_timeout... yes
checking for curlopt_timeout_ms... no
checking for curlopt_low_speed_limit... yes
checking for curlopt_low_speed_time... yes
checking for curlopt_max_send_speed_large... yes
checking for curlopt_max_recv_speed_large... yes
checking for curlopt_maxconnects... yes
checking for curlopt_closepolicy... yes
checking for curlopt_fresh_connect... yes
checking for curlopt_forbid_reuse... yes
checking for curlopt_connecttimeout... yes
checking for curlopt_connecttimeout_ms... no

But there is no check to see if the definition is available in curb_easy.c prior to using them:

  if (rbce->timeout_ms && rbce->timeout_ms > 0) {
    curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, rbce->timeout_ms);
  }
  curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, rbce->connect_timeout);
  curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, rbce->connect_timeout_ms);

so compiling curb_easy.c fails:

compiling curb_easy.c
curb_easy.c: In function ‘ruby_curl_easy_setup’:
curb_easy.c:2114: error: ‘CURLOPT_TIMEOUT_MS’ undeclared (first use in this function)
curb_easy.c:2114: error: (Each undeclared identifier is reported only once
curb_easy.c:2114: error: for each function it appears in.)
curb_easy.c:2117: error: ‘CURLOPT_CONNECTTIMEOUT_MS’ undeclared (first use in this function)
make: **\* [curb_easy.o] Error 1

These definitions were first added to libcurl in version 7.16.2 and CentOS 5 has 7.15.5. See: https://curl.haxx.se/changes.html#7_16_2 

Could you please add a check to see if the CURLOPT_TIMEOUT_MS and CURLOPT_CONNECTTIMEOUT_MS are defined or check that the LIBCURL_VERSION_NUM >= 0x071002 prior to using them?

Thanks,
Andrew

**Comment by IanMcNelly** [comment]
Experiencing the same error with curl version 7.15.5 and centos-release-5-8.el5.centos

checking for curlopt_timeout... yes
checking for curlopt_timeout_ms... no
checking for curlopt_low_speed_limit... yes
checking for curlopt_low_speed_time... yes
checking for curlopt_max_send_speed_large... yes
checking for curlopt_max_recv_speed_large... yes
checking for curlopt_maxconnects... yes
checking for curlopt_closepolicy... yes
checking for curlopt_fresh_connect... yes
checking for curlopt_forbid_reuse... yes
checking for curlopt_connecttimeout... yes
checking for curlopt_connecttimeout_ms... no
...
curb_easy.c:2122: error: ‘CURLOPT_TIMEOUT_MS’ undeclared (first use in this function)
curb_easy.c:2122: error: (Each undeclared identifier is reported only once
curb_easy.c:2122: error: for each function it appears in.)
curb_easy.c:2125: error: ‘CURLOPT_CONNECTTIMEOUT_MS’ undeclared (first use in this function)

**Comment by taf2** [comment]
Perhaps this is fixed now with: a57f214
