### ISSUE TITLE
Curl::Err::ReadError: Failed to open/read local data from file/application

### ISSUE THREAD

**Issue by JackTing** [taf2/curb#290]
On Win7 64Bit:
Curl::Easy.new(url) do|curl|
           curl.multipart_form_post=true
           curl.http_post(Curl::PostField.file('file', "file")) 
end

Curl::Err::ReadError: Failed to open/read local data from file/application......

Why? please!

**Comment by taf2** [comment]
"file" is not on your file system?

On Saturday, March 26, 2016, JackTing <notifications@github.com> wrote:

> Curl::Easy.new(url) do|curl|
> curl.multipart_form_post=true
> curl.http_post(Curl::PostField.file('file', "file"))
> end
>
> Curl::Err::ReadError: Failed to open/read local data from
> file/application......
>
> Why? please!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/taf2/curb/issues/290>
>


-- 
*Todd Fisher*
Tel: +1 (410) 394-9424 | Toll Free: +1 (800) 577-1872
todd@calltrackingmetrics.com | calltrackingmetrics.com

**Comment by JackTing** [comment]
file is local:"c:/test.png"
my code:
 url="http://121.41.123.123/attachments.json"
files=["c:/users/a.skb","c:/users/a.png"]
curl=Curl::Easy.new(url)
curl.follow_location = true
curl.multipart_form_post=true
 i=0
 posts=files.collect{|f|
     i+=1
    Curl::PostField.file('file#{i}',f)
}
curl.http_post(posts)

this code on OSX is work,but on Windows 7 not work
sometimes on  Winodws7 first will work,when second will error:
some error is:
1、 Curl::Err::ReadError: Failed to open/read local data from file/application......
2、Too many open files......

**Comment by taf2** [comment]
sounds like maybe the open file limit on windows 7 is different from osx...  how many files do you have open in files array?

**Comment by JackTing** [comment]
two files
one file will error!

**Comment by taf2** [comment]
What about in the latest gem release?

**Comment by JackTing** [comment]
I test the curb version is  0.8.5、0.9.1、 0.9.3
the last version is still error!

**Comment by matisoffn** [comment]
I'm having the same problem, my file is not on my local filesystem.  It's stored in S3.  How can I accomplish this with a remote file?

**Comment by matisoffn** [comment]
Still having this problem..

**Comment by matisoffn** [comment]
When I add this line to my server-side `echo json_encode($_FILES);` I see this in the response:

```json
{"file":{"name":"myfile.pdf","type":"","tmp_name":"","error":1,"size":0}}
```

For some reason, curb isn't attaching the file.

**Comment by r1goo** [comment]
Im having the same problem, but my file it is not local, instead its an URL from Amazon S3, any advice? Solution?

@used_car = UsedCar.find(id_used_car)
      
      @uri = "https://api.mercadolibre.com/pictures?access_token=..."
      c = Curl::Easy.new(@uri)
      c.multipart_form_post = true
      
      @path = @used_car.image4.to_s
      
      c.http_post(Curl::PostField.file('file',@path))

Do i have some ort of solution for this? Thankx in advance!

**Comment by pjcruz13** [comment]
Hello,
I am having issues curl  Failed to open/read local data from file/application. Below is my code:
curl -X POST  http://ipaddress/infosilemEnterprise/API/CourseScheduling/CourseScheduling.asmx?SOAP -H 'Authorization: Bearer 829746c4-32c8-45e3-9bb0-761de1125b8' -F 'file=@d:\datatel\coll18\dev\apphome\_HOLD_\InfoSilem_Sections.xml'
I have verified that the file is in the location specified
