### ISSUE TITLE
easy.rb:68:in `perform': select(): Operation now in progress (RuntimeError) with ruby 1.8.7 (EL6)

### ISSUE THREAD

**Issue by vinzent** [taf2/curb#304]
I can't use curb on EL6 (Ruby 1.8.7, curl 7.19.7) anymore. Latest working version is 0.9.1. 

From 0.9.2 on I see the error below.

Test script:

```
require 'rubygems'
require 'curb'

http = Curl.get("http://localhost")
puts http.body_str
```

Output with curb version 0.9.3 and 0.9.2

```
/usr/lib/ruby/gems/1.8/gems/curb-0.9.3/lib/curl/easy.rb:68:in `perform': select(): Operation now in progress (RuntimeError)
        from /usr/lib/ruby/gems/1.8/gems/curb-0.9.3/lib/curl/easy.rb:68:in `perform'
        from /usr/lib/ruby/gems/1.8/gems/curb-0.9.3/lib/curl.rb:17:in `http'
        from /usr/lib/ruby/gems/1.8/gems/curb-0.9.3/lib/curl.rb:17:in `http'
        from /usr/lib/ruby/gems/1.8/gems/curb-0.9.3/lib/curl.rb:22:in `get'
        from /tmp/test.rb:4
```

**Comment by taf2** [comment]
I don't have time to investigate but I'll happily accept patches to fix this.

**Comment by vinzent** [comment]
version tags would be nice to have a quick entrypoint what changed between the versions.

**Comment by vinzent** [comment]
032339e41513b4f37768ee2e2812c8c346c164f4 seems to be 0.9.1
and c6f0a25bf5f698456196ccc52c72e667fad6cb18 0.9.2 - lets try to figure out what changed now.

**Comment by keen99** [comment]
+1 - just got this too with 0.9.3
