### ISSUE TITLE
incomatible versions of curb 0.9.3 and curl-7.51.0

### ISSUE THREAD

**Issue by majioa** [taf2/curb#307]
I've compiled version of `curb` 0.9.3 for the `curl` version `libcurl-7.51.0`. Then during loading a get the following exception:

    incompatible library version - /usr/local/home/majioa/git/vpnapp/modern/.bundle/gems/curb-0.9.3/lib/curb_core.so
    /usr/local/home/majioa/git/vpnapp/modern/.bundle/gems/curb-0.9.3/lib/curl.rb:1:in `require'

How this should be fixed?

**Comment by andoriyu** [comment]
That be nice...

**Comment by taf2** [comment]
Possibly run 

gem prestine?
