### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by voxik** [taf2/curb#310]
Curb was always licensed under Ruby license as far as I can say. At least the LICENSE file looks to be Ruby license and Ruby license is also mentioned in plenty of file headers as well as it is referenced in README. But the .gemspec file says (since c6f0a25bf5f698456196ccc52c72e667fad6cb1) it is MIT. Could you please fix the license in the .gemspec file, since it seems to be the only place where the MIT is mentioned?

**Comment by taf2** [comment]
all set
