### ISSUE TITLE
curb not retaining keep-alive connection?

### ISSUE THREAD

**Issue by kikonen** [taf2/curb#312]
With curb 0.9.3 (possibly related to #152)

```ruby
easy = Curl::Easy.new("https://api.test.com/rest/api/path")
easy.verbose = true
easy.perform
easy.perform
```

I was expecting connection to be reused at second "perform", but based into "netstat" and curl logging output that is not happening. In comparison "httpclient" (gem which I'm planning to replace with curb) is seemingly keeping connection alive (according to netstat).

I've tried to search if I've missed something in configuration of curb, but so far I've failed to see what I'm doing wrong.

Full trace (if it helps to provide answer)
```
[96] pry(main)> easy = Curl::Easy.new("https://api.test.com/rest/api/path")
=> #<Curl::Easy https://api.test.com/rest/api/path>
[97] pry(main)> easy.verbose = true
=> true
[98] pry(main)> easy.perform
*   Trying 6.6.6.6...
* Connected to api.test.com (6.6.6.6) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* NPN, negotiated HTTP1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*        < cut... cert data here >
* 	 SSL certificate verify ok.
> GET /rest/api/path HTTP/1.1
Host: api.test.com
Accept: */*

< HTTP/1.1 200 OK
< Server: nginx/1.10.0
< Date: Tue, 24 Jan 2017 09:02:31 GMT
< Content-Type: application/json
< Content-Length: 3268
< Connection: keep-alive
< X-Powered-By: Undertow/1
< Strict-Transport-Security: max-age=15768000
<
* Connection #0 to host api.test.com left intact
=> true
[99] pry(main)> easy.perform
*   Trying 6.6.6.6...
* Connected to api.test.com (6.6.6.6) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* SSL re-using session ID
* NPN, negotiated HTTP1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*        < cut... cert data here >
* 	 SSL certificate verify ok.
> GET /rest/api/path HTTP/1.1
Host: api.test.com
Accept: */*

< HTTP/1.1 200 OK
< Server: nginx/1.10.0
< Date: Tue, 24 Jan 2017 09:02:32 GMT
< Content-Type: application/json
< Content-Length: 3268
< Connection: keep-alive
< X-Powered-By: Undertow/1
< Strict-Transport-Security: max-age=15768000
<
* Connection #0 to host api.test.com left intact
=> true
```

**Comment by taf2** [comment]
Try:

```
Curl.get("https://api.test.com/rest/api/path") {|http| http.verbose = true }
Curl.get("https://api.test.com/rest/api/path") {|http| http.verbose = true }
```

?

**Comment by kikonen** [comment]
Sadly not noticing change in behavior.

**Comment by kikonen** [comment]
Isn't this related into this commit:

https://github.com/taf2/curb/commit/e3126a874ccfae8adf4cd845b2d86f0f2aeda932

**Comment by taf2** [comment]
looks that way.  as I recall that commit squashed a bug with GC causing a crash...  I think as I commented if we can add a switch to enable single use mode vs multi use mode...

**Comment by mkauf** [comment]
The GC bug has been fixed with commit 5a5f3a9. I think that it's safe to revert commit e3126a8.

**Comment by kikonen** [comment]
Regarding GC bug, I was able to get consistent memory corruption with combination "curb + oj". I.e. doing lots of request using curb and parsing them with oj. Eventually data parsing in oj gives out random "lost data" corruption. When not using curb I'm not able to see such. So I deduce that there must be some pending memory access bug in curb (or libcurl) (https://github.com/ohler55/oj/issues/330).

**Comment by kikonen** [comment]
So, any changes that you could provide option. For GC safety (i.e. due to issues noticed in https://github.com/ohler55/oj/issues/330), I'm now running with following pattern

```ruby
        was_gc_disabled = GC.disable
        begin
          curl.http_xxxx
        ensure
          GC.enable unless was_gc_disabled
        end
```
So GC shouldn't be issue.

**Comment by kikonen** [comment]
ping? any changes of getting back persisted connections?

**Comment by mlartz** [comment]
+1 Glad I found this issue ... I've been beating my head wondering why Curb wasn't reusing the connections.  I've been "benchmarking" a bunch of different clients for use as an elasticsearch-transport, as well as a REST client.  Curb has all the features that I need (mainly performance and complete/robust SSL) and has good performance, but looses out to patron (which lacks complete SSL support) without persistent connections.

**Comment by taf2** [comment]
@mlartz sorry aware of the issue just need time to debug.  If you use this in your Gemfile you'll have the version of Curb that was sharing connections

gem 'curb', '0.9.2'

**Comment by kikonen** [comment]
It looks like cset disabling connection sharing logic is earlier than 0.9.2 (see comments)

i.e. it looks like 0.9.1 is version still doing connection sharing
```ruby
gem 'curb', '0.9.1'
```

**Comment by dElogics** [comment]
Has been starting to bother me too.

**Comment by taf2** [comment]
Should be fixed in 0.9.4

**Comment by dElogics** [comment]
Thanks!

**Comment by kikonen** [comment]
Been running 0.9.4 now for few days in test environment (without that GC hack I had to use earlier), and so far haven't noticed issues.
