### ISSUE TITLE
Suddenly getting Curl::Err::OutOfMemoryError

### ISSUE THREAD

**Issue by rvyas** [taf2/curb#351]
I recently update to ruby 2.4.4 and 2.5.1 and getting an exception with simple http_get command:
`[Curl::Err::OutOfMemoryError] - Out of memory`

/vendor/bundle/gems/curb-0.9.4/lib/curl/easy.rb:73:in 'perform'   
/vendor/bundle/gems/curb-0.9.4/lib/curl/easy.rb:296:in 'http'   
/vendor/bundle/gems/curb-0.9.4/lib/curl/easy.rb:296:in 'http_get'   

Could not identify the issue. Any help is appreciated.
Curb Version: 0.9.4 
curl 7.19.7

**Comment by rvyas** [comment]
Temporary moved to `httpclient` and `rubyntlm` which is working ok.

**Comment by taf2** [comment]
do you have any example code that replicates the issue?

**Comment by rvyas** [comment]
I am using curb as adapter for HTTPI
```
HTTPI.adapter = :curb
request = HTTPI::Request.new
request.headers['Content-Type'] = 'application/json'
request.url = <url>
request.auth.ntlm(<user>, <passphrase>)
response = HTTPI.get(request)
```

**Comment by taf2** [comment]
@rvyas thanks!  Let me see if I can create a test.  I bet it's not getting a chance to GC or something similar.  In the meantime you might try curb 0.9.3 and see if you still get memory leaks on ruby2.5.1?

**Comment by robuye** [comment]
This is a very old `curl` version (Nov 2009) and gets barely any support for this reason. Can you try upgrading?

**Comment by rvyas** [comment]
Sorry couldnt get time to look into this.
@taf2  - I tried 0.9.3 - same issue.
@robuye  - Updating `curl` version is no more an option for me!

**Comment by rvyas** [comment]
Few more details:
The url with http**s** given `Curl::Err::OutOfMemoryError` error!!
Fetching from http works ok.

**Comment by taf2** [comment]
@rvyas I guess i need more context to figure it out... if I just run that one script in a loop?   or is it a very large response body?  You might try 
```
http = Curl::Easy.new(url)
http.on_body {|d| puts d; d.size }
http.on_complete {
puts "all done"
}
```

that will avoid buffering the full response body.

**Comment by taf2** [comment]
Let me know if you can replicate the issue otherwise assuming this issue is resolved now.

**Comment by rvyas** [comment]
It does not seems to be the response body but response headers or ssl encrypted data which is causing the memory leaks due to gssnegotiate auth and https.

**Comment by rvyas** [comment]
ok, I think I can reproduce. For me, the issue is with https (http secure) calls only. http works ok.

Hope this helps.

```ruby
http = Curl::Easy.new("http://www.google.com")
http.on_complete {
  puts "all done"
}
http.perform
puts http.status
```

```
all done
200 OK
```
With https:
```ruby
http = Curl::Easy.new("https://www.google.com")
http.on_complete {
  puts "all done"
}
http.perform
puts http.status
```

```
all done
(Curl::Err::OutOfMemoryError) curb-0.9.9/lib/curl/easy.rb:79:in `perform': HTTP/1.1 200 Connection established

```

**Comment by taf2** [comment]
So this might be an issue with the SSL library you have installed with libcurl?

**Comment by taf2** [comment]
For me on Amazon linux 1 and 2, and OSX
```
2.5.3 :001 > http = Curl::Easy.new("https://www.google.com")
 => #<Curl::Easy https://www.google.com>
2.5.3 :002 > http.on_complete {
2.5.3 :003 >       puts "all done"
2.5.3 :004?>   }
 => nil
2.5.3 :005 > http.perform
puts http.status
all done
 => true
2.5.3 :006 > puts http.status
200 OK
 => nil
```

Can you try re-compiling libcurl?

**Comment by rvyas** [comment]
ok, will try (bdw, we recently updated libcurl as well).

**Comment by rvyas** [comment]
Ok, so no luck. Still getting same error.
Can you give me some pointers on how i can debug like what exact call is causing out of memory error? That will help.

It seems to be https with gssnegotiate. SSL library does work ok as I am able to make https calls using ruby's net/http module but it is the authentication using auth.gssnegotiate.

Thanks.

**Comment by taf2** [comment]
Can you try with Curl::Multi.autoclose = true and see if you still get memory issues?

**Comment by rvyas** [comment]
I am still getting same error with Curl::Multi.autoclose = true set as below.

```
Curl::Multi.autoclose = true
http = Curl::Easy.new("https://www.google.com")
http.on_complete {
  puts "all done"
}
http.perform
puts http.status
```
