### ISSUE TITLE
Handle compression?

### ISSUE THREAD

**Issue by hartator** [taf2/curb#353]
Is there a way to pass the `--compress` parameter to curl via curb?

**Comment by hartator** [comment]
Mainly to handle gzip and brotli compression. I can dig into it if no one already looked at it.

**Comment by robuye** [comment]
It should be possible using `#encoding=`, i.e.

```ruby
    c = Curl::Easy.new(@url)
    c.encoding = 'gzip'
    c.perform
```

Curl will perform automatic decoding of the response and it may not be obvious if the content was encoded in first place or not. Look for the `Content-Encoding` response header, if it's `gzip` then the server did use compression.

Setting `encoding=` makes curl *ask* for compression, but it's up to server how to respond.

**Comment by taf2** [comment]
c.encoding should do the trick closing this out.
