### ISSUE TITLE
Installation of Curb on Win7 - How?

### ISSUE THREAD

**Issue by luke-hill** [taf2/curb#356]
Currently on phone. But I’ll try

Installation links on readme are dead. I am using. 

Ruby 2.5.1 - Win7 - 64bit

Can I use curb as I am tooled with MYSYS??

Do I need to downgrade to 2.3?? (This is EOL in 6months)

What url works. I can’t find any develop links on the haxx.se page.

**Comment by taf2** [comment]
Not sure- I don't have a windows computer handy.   Doesn't windows have a Linux subsystem now?   I guess make sure you have libcurl installed and that curl-config is accessible to your path?

**Comment by luke-hill** [comment]
I downgraded to 2.3 for now. Sadly I don't think on Windows you can use Curb with Ruby 2.4+ I spent a good few weeks triaging this and the installation just didn't work.
