### ISSUE TITLE
curb installation problems

### ISSUE THREAD

**Issue by volkanunsal** [taf2/curb#38]
Hi,

I'm trying to install curb and keep getting errors, apparently caused by libcurl not being on the PATH--even though it is. 

http://gist.github.com/460344

**Comment by ccoenen** [comment]
@volkanunsal your problem included similar problems i just ran into. I may have an installation method. If you could give it a try i'd be very thankful.

Instructions are included in this pull request.
https://github.com/taf2/curb/pull/233

**Comment by ccoenen** [comment]
Voting to close this ancient ticket.
