### ISSUE TITLE
unknown keywords: whitelist_classes, whitelist_symbols

### ISSUE THREAD

**Issue by armanstackify** [taf2/curb#382]
Hi guys, I tried to install curb in my rails app however I got this error below:
$ gem install curb -v '0.9.9' or gem install curb
ERROR:  While executing gem ... (ArgumentError)
    unknown keywords: whitelist_classes, whitelist_symbols

By the way, I'm using ruby 2.6.0preview3

Any ideas how to solve this issues?

**Comment by taf2** [comment]
There should be a more detailed stacktrace in the mkmf.log file in the gem source directory- if you can provide that it will help here

**Comment by luke-hill** [comment]
That error is suspiciously similar to the rubocop one, and it was caused by a Ruby Bump combined with YAML having a major bump.

See here: https://github.com/rubocop-hq/rubocop/pull/6470

So it's likely @taf2 that on Ruby2.6 we may need a conditional to handle the kwargs

**Comment by luke-hill** [comment]
@armanstackify - Do you get the same error on the latest Ruby 2.5
Also 2.6 is out of preview now, so use a stable one (However it's likely the 2.6 latest cut will still fail)
Once you've confirmed that 2.5 works and 2.6 doesn't let us know. Or if they both work ... great!
