### ISSUE TITLE
[OSX Catalina] Library not loaded: @rpath/libgssapi_krb5.2.2.dylib

### ISSUE THREAD

**Issue by neumanrq** [taf2/curb#401]
Hi 👋

Unfortunately, when trying to install `curb` v0.9.10 within a Gemfile of a Rails app, I can't make the installation work. If I do a `gem install curb` on my system, it works fine. 

OS: macOS Catalina, 10.15.1
Ruby: MRI v2.6.4 (also tested with v2.6.5)

Here's the full error:
```
LoadError: dlopen(/Users/robin/.rvm/gems/ruby-2.6.4/gems/curb-0.9.10/lib/curb_core.bundle, 9): Library not loaded: @rpath/libgssapi_krb5.2.2.dyli$
  Referenced from: /Users/robin/.rvm/gems/ruby-2.6.4/gems/curb-0.9.10/lib/curb_core.bundle
  Reason: image not found - /Users/robin/.rvm/gems/ruby-2.6.4/gems/curb-0.9.10/lib/curb_core.bundle
```

What I've tried so far:

* `brew reinstall curl`
*  `brew install krb5`

Does anybody have an idea how to proceed?

**Comment by pokrovskyy** [comment]
I managed to overcome this by symlinking the original `/usr/lib/libgssapi_krb5.dylib` provided by Catalina in `/usr/local/lib/libgssapi_krb5.2.2.dylib` via: 
```
sudo ln -s /usr/lib/libgssapi_krb5.dylib /usr/local/lib/libgssapi_krb5.2.2.dylib
```

**Comment by neumanrq** [comment]
Good news! I've re-evaluated this within a fresh Rails 6 application under Ruby 2.6.5 together under Catalina 10.15.4 and I cannot reproduce it any longer. Thanks @pokrovskyy for your tip, which seems to work for 10.15.1.

**Comment by sophie-truong-goldenowl** [comment]
I got the very same error just now

```
/Users/usera/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': dlopen(/Users/usera/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/curb-0.9.10/lib/curb_core.bundle, 9): Library not loaded: @rpath/libssh2.1.dylib (LoadError)
  Referenced from: /Users/usera/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/curb-0.9.10/lib/curb_core.bundle
  Reason: image not found - /Users/usera/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/curb-0.9.10/lib/curb_core.bundle
```

And I tried

```
brew reinstall curl
brew install krb5
sudo ln -s /usr/lib/libgssapi_krb5.dylib /usr/local/lib/libgssapi_krb5.2.2.dylib
```

I also tried to reinstall ruby. 

And tried (https://stackoverflow.com/a/59184347/2724342)

```
brew switch openssl 1.0.2t
```

But it does still not work! I don't know what to try next.

**Comment by timlewandowski** [comment]
> But it does still not work! I don't know what to try next.

Same for me. Have you solved your problem by any chance @sophie-truong-goldenowl ?
