### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by Frenchcooc** [taf2/curb#407]
Hi,

I've made a quick search on the README + the past issues and haven't seen any ways to propose a sponsorship. Is this something that you would be interested in?

Happy to talk about it. I'm Corentin - developer advocate at [Bearer.sh](https://github.com/bearer)

**Comment by taf2** [comment]
Ha - I think best way to help is to join my company - calltrackingmetrics.com - we need more hackers to solve more problems :100:
