### ISSUE TITLE
Can't set CURLOPT_IPRESOLVE

### ISSUE THREAD

**Issue by abevoelker** [taf2/curb#416]
I need to connect to a server that has flaky IPv6 support, so I'd like to use curl's ability to force IPv4 (see CLI short option `-4`). But if I try to tell curb to set [CURLOPT_IPRESOLVE](https://curl.haxx.se/libcurl/c/CURLOPT_IPRESOLVE.html) it seems it doesn't support it:

```
Curl::Easy.perform("http://example.com") do |curl|
  curl.set(:ipresolve, :v4)
end
# TypeError (Curb doesn't support setting ipresolve [#113] option)
```

**Comment by taf2** [comment]
@abevoelker 

You need easy.resolve_mode=

```
easy.resolve_mode=:auto
```
