### ISSUE TITLE
on_failure receive incorrect argument

### ISSUE THREAD

**Issue by valodzka** [taf2/curb#421]
on_failure result for reproducer: 

`[#<Curl::Easy https://httpstat.us/503>, [Curl::Err::CurlOK, "No error"]]
`

Expected result:

`[#<Curl::Easy https://httpstat.us/503>, [Curl::Err::ServiceUnavailable, "Service Unavailable"]]
`

Reproducer:

```
require 'curb'
responses = {}
requests = ['https://httpstat.us/503']
m = Curl::Multi.new

requests.each do |url|
  responses[url] = ""
  c = Curl::Easy.new(url) do|curl|
    curl.follow_location = true
    curl.on_body{|data| responses[url] << data; data.size }
    curl.on_success {|easy|
      puts "ok"
    }
    curl.on_complete{|x, a|
      p 'compl'
      p [x, a]
    }
    curl.on_failure{|e, code|
      p [e, code, text]
    }
  end
  m.add(c)
end

m.perform 

requests.each do|url|
  puts responses[url]
end

```

**Comment by taf2** [comment]
@valodzka - sorry for the confusion on this.   Curl::Err::CurlOK is correct here.   If you want the http status code that is available on the easy handle via easy.response_code.   The reason you get a Curl::Err::CurlOK in your example is that the request is completed without any issues the libcurl library did got all the bytes back from the server and handled everything correctly.  In the example, the server is replying with a status code of 503, but that doesn't mean anything failed during the request/response from the eyes of the client it's libcurl error status is okay.
