### ISSUE TITLE
New version request

### ISSUE THREAD

**Issue by uvlad7** [taf2/curb#426]
Please provide new version on rubygems.org.
Thanks!

**Comment by RGBD** [comment]
What's the best place to track what's blocking the next release, by the way?

**Comment by taf2** [comment]
@RGBD let me check - i don't think anything just need to run tests and double check commits and push the buttons...  I'll try to find time for this today / weekend.

**Comment by taf2** [comment]
pushed 1.0 - thanks for reminding me :+1:
