### ISSUE TITLE
LICENSE file contents does not match MIT license in the gemspec file

### ISSUE THREAD

**Issue by graaff** [taf2/curb#436]
The license in the gemspec file was changed to MIT, but the contents of the LICENSE file and the README.md still refer to the Ruby license. Based on this it's not clear to me what the license is. Could you clarify this by either updating the LICENSE file and README.md or the gemspec?

**Comment by jackorp** [comment]
I'd say it is Ruby based on https://github.com/taf2/curb/issues/420 and https://github.com/taf2/curb/issues/310

The template that is used for updates is probably wrong: https://github.com/taf2/curb/blob/a1076f848e84b26afe8fda1cf81c31f68539f7ab/lib/curb.gemspec.erb#L39 . Each update seems to rewrite the license in gemspec to MIT from Ruby and the change seems to come from the template.
