### ISSUE TITLE
Build against curl-impersonate

### ISSUE THREAD

**Issue by randy-girard** [taf2/curb#438]
Hello,

I was curious if its possible to build this against https://github.com/lwthiker/curl-impersonate. I was able to build that project and run it, but have not been able to build this against that project, it doesn't appear.

**Comment by taf2** [comment]
Sorry not sure - if you send a pull request I can look into merging.

**Comment by uvlad7** [comment]
@randy-girard `gem install curb -- --with-curl-dir=/opt/pf-pkg/curl-impersonate --with-curllib=curl-impersonate-chrome` worked for me just fine

**Comment by uvlad7** [comment]
@taf2 would you accept a PR to expose [`curl_easy_impersonate`](https://github.com/lwthiker/curl-impersonate?tab=readme-ov-file#libcurl-impersonate) if linked to impersonate version? And probably add some extconf params to configure which impersonate target to use and to ensure `curl-config` isn't used (impersonate doesn't provide it)

**Comment by taf2** [comment]
Yeah - seems cool
