### ISSUE TITLE
Segfault in Multi after upgrading to v1.0.3

### ISSUE THREAD

**Issue by wintersolutions** [taf2/curb#440]
After a upgrade to curb v1.0.3 (from 1.0.1) I'm getting a Core Dump/Segmentation fault in my unit tests (RSpec):

```
/builds/redacted/vendor/bundle/ruby/3.1.0/gems/curb-1.0.3/lib/curl/easy.rb:69: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
```

This Bug is reproducible on the "standard" ruby:3.1.3 Docker image (https://hub.docker.com/_/ruby) with Debian Bullseye and Curl v.7.74.0-1.3+deb11u3 running in a K8s container. However I cannot reproduce it on my Workstations with Manjaro Linux and curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0. The Curb version 1.0.1 works everywhere.

Here are  the important bits of the Segfault:

```
-- Control frame information -----------------------------------------------
c:0147 p:---- s:0923 e:000922 CFUNC  :perform
c:0146 p:0042 s:0919 E:002050 METHOD /builds/redacted/vendor/bundle/ruby/3.1.0/gems/curb-1.0.3/lib/curl/easy.rb:69
```

```
-- C level backtrace information -------------------------------------------
/usr/local/lib/libruby.so.3.1(rb_print_backtrace+0x11) [0x7fb82f4af348] vm_dump.c:759
/usr/local/lib/libruby.so.3.1(rb_vm_bugreport) vm_dump.c:1045
/usr/local/lib/libruby.so.3.1(rb_bug_for_fatal_signal+0xf0) [0x7fb82f2ad800] error.c:821
/usr/local/lib/libruby.so.3.1(sigsegv+0x49) [0x7fb82f405429] signal.c:964
/lib/x86_64-linux-gnu/libpthread.so.0(__restore_rt+0x0) [0x7fb82f1a4140]
/usr/local/lib/libruby.so.3.1(ruby_sip_hash13+0x58) [0x7fb82f3bf198] siphash.c:422
/usr/local/lib/libruby.so.3.1(rb_str_hash+0x46) [0x7fb82f41dc96] string.c:3522
/usr/local/lib/libruby.so.3.1(RB_FL_TEST_RAW+0x0) [0x7fb82f2e81c6] hash.c:173
/usr/local/lib/libruby.so.3.1(RHASH_AR_TABLE_P) internal/hash.h:150
/usr/local/lib/libruby.so.3.1(ar_lookup) hash.c:1099
/usr/local/lib/libruby.so.3.1(hash_stlike_lookup) hash.c:2073
/usr/local/lib/libruby.so.3.1(rb_hash_aref) hash.c:2105
/builds/redacted/vendor/bundle/ruby/3.1.0/gems/curb-1.0.3/lib/curb_core.so(rb_curl_mutli_handle_complete+0x1d0) [0x7fb8287ae100] curb_multi.c:307
/builds/redacted/vendor/bundle/ruby/3.1.0/gems/curb-1.0.3/lib/curb_core.so(rb_curl_multi_read_info+0x30) [0x7fb8287aef5c] curb_multi.c:392
/builds/redacted/vendor/bundle/ruby/3.1.0/gems/curb-1.0.3/lib/curb_core.so(ruby_curl_multi_perform) curb_multi.c:541
```

Sadly I can't share the Ruby code that leads to the Exception, its part of a private/unrleased software package and the calling code is hidden behind layers of abstractions. Its a basic Multi GET with around 500 simulatenous connections. However I can produce the complete log if necessary.

**Comment by taf2** [comment]
@wintersolutions sorry for this I identified the issue and it should* be fixed/ resolved now with the release of 1.0.4

I noticed this as well and should have pulled 1.0.3 / 2 before this got out.   I'm going to push 1.0.4 into our production environment tomorrow morning and will let you know if we see similar errors.

**Comment by wintersolutions** [comment]
@taf2 No need to be sorry and don't hurry on my behalf, I can stay on the 1.0.1 version for a long time. Just wanted to let you guys know about the regression. Thanks for all your work and a good start into 2023!

**Comment by taf2** [comment]
We've been running 1.0.4 through a few million transactions this morning and no segv - going to close this one out.

**Comment by wintersolutions** [comment]
@taf2 Can confirm that v1.0.5 works flawless here too. Thanks for all the work!

**Comment by taf2** [comment]
@wintersolutions yes have it running in multiple production workloads
