### ISSUE TITLE
curb should expose curl_easy_setopt

### ISSUE THREAD

**Issue by richmeyers** [taf2/curb#49]
As detailed in issue #48, curb does not directly allow setting certain timeout options available in curl. This would have been a minor inconvenience if curb exposed curl_easy_setopt call (and corresponding multi-call, if any). Even without any CURLOPT_\* constants defined I could still pass appropriate magic numbers to curl_easy_setopt and have a workaround for timeout functionality until a better solution is put in place. Currently I have no choice but to edit C extension code, followed by distributing and installing custom packages to/on a number of development and production systems.

Curb should expose curl_easy_setopt, perhaps with a warning that it is possible to break things by passing certain values to it (e.g. options that take C strings as arguments for example), for cases when it does not provide a "native" interface to some functionality.

**Comment by michael-creed** [comment]
Hi - firstly, what a great package curb is, and language ruby is.  I'm just starting out with learning ruby and using it to write some Rspec test cases for my team to use.

I'm currently having a related issue trying to setopt for Curl::CURLOPT_RESOLVE, receiving the message that setting that option is not supported.

I'm looking to replicate the following command:

curl --resolve "mytest.com:443:127.0.0.1" https://mytest.com

I have a working test that uses ssl_verify_host = false, which is working for most of my test cases, but is not working for end to end tests that need the hostname to be set.

Why on earth would you want to do that?  The load balancers I'm connecting to perform logic based on the url used for the connection (SNI?) and therefore this drops my connection request.

I'm looking at invoking the command line option to do this testing at the moment, which would be a real shame.

Thank you very much for any help you can provide.

**Comment by driehuis** [comment]
Implementing a setter interface to CURLOPT_RESOLVE would be rather a challenge, as it involves setting up and maintaining a list of structs just to hold the value).

As an aside, I can confirm @apollo-io 's issue: lack of SNI support is causing hard to debug issues with programs written to use Curb (once you dig out the underlying OpenSSL error, the user is likely to go on a wild goose chase for TLSv1 vs SSLv3 mismatches).

The problem exhibits itself when connecting to an SNI enabled server on a different IP than that given in DNS. This requires the Curb user to mess around with tricks like giving the URL as https://127.0.0.1:443/ whilst setting the requested server in the headers["Host"] parameter. In that case, OpenSSL doesn't know it should pass the Host header to the HELLO negociation, and SNI fails with a rather confusing error message 14077410 from OpenSSL.

The easy.set interface may not be the optimal way to implement this. Perhaps an easier way is to extend the URL syntax to allow specifying https://www.example.com:443:127.0.0.1/, rewriting that to https://www.example.com/ before passing it to Curl and set the CURLOPT_RESOLVE structure as required

Yet another alternative is to add an easy.connect_ip attribute that optionally overrides the DNS lookup (again, probably using CURLOPT_RESOLVE under the hood).

**Comment by taf2** [comment]
@driehuis are you saying curb doesn't support SNI?    This seems like something, that should be supported by default...  e.g.

```
res = Curl.get("https://www.google.com/")
puts res.header_str
puts res.body_str
```

This should automatically be doing an SNI lookup?

**Comment by driehuis** [comment]
@taf2: Curb does support SNI, but only if you wish to connect to the IP address as resolved through DNS.

If you need to check stuff behind a load balancer, or if for other reasons you need to avoid the DNS lookup, exposing the functionality of CURLOPT_RESOLVE is required to make SNI work. The trickery that I described above only works for plain HTTP and fails miserably for SSL (as my users deftly pointed out, rubbing in that the PHP bindings to curl do expose this feature. I told 'm where to stuff it, but I digress).

My use case is checking if multiple backends for the same servername are all in sync, so IP address is the only discriminator.
